### ISSUE TITLE
Redirecting on IOS

### ISSUE THREAD

**Issue by snowybeast13** [microsoft/aad_b2c_webview#14]
Hi guys, i have issue with redirection after login on IOS. Tried different redirect URI's and nothing is happening. In logs on azure I can see that user is successfully log in, but after i click  Sign in button nothing is happening. Any idea how to solve redirection issue? Thank you

**Comment by mohanajuhi166** [comment]
@snowybeast13 thanks for bringing this to our notice. I will have a look soon .

**Comment by SzczygielDev** [comment]
I also run into same issue, I tried few things and in my case it was not executing onPageFinished of WebViewController inside ADB2CEmbedWebView after successfully signin in. I found that onUrlChange of WebViewController captures url change, so this snippet allowed me to sign in on iOS:

`
onUrlChange: (change) { final Uri response = Uri.dataFromString(change.url!); onPageFinishedTasks(change.url!, response); }
`

I don't know whether its proper solution and will work in all cases.

**Comment by filip8600** [comment]
The suggestion also worked for me. 

I also then disabled the old "onPageFinished" - as to not get double events emitted on Android.
