### ISSUE TITLE
Not compatible with webview_flutter ^4

### ISSUE THREAD

**Issue by FullstackWEB-developer** [microsoft/aad_b2c_webview#18]
I would like to know if support for webview_flutter ^4 is on the current roadmap.
If not, can I contribute a new version that supports webview_flutter ^4?
```[tasklist]
### Tasks
- [x] compatible with webview_flutter ^4.2.2
```

**Comment by mohanajuhi166** [comment]
Hi @FullstackWEB-developer ,You can contribute it to the repository. We appreciate the same
