### ISSUE TITLE
Redirect uri

### ISSUE THREAD

**Issue by eugedebe** [microsoft/aad_b2c_webview#23]
Hi, 

First of all thanks for this library

I have implemented the code given in the example in pubdev. After pressing the button, I am able to receive in the callbacks of the widget (onIDToken and onAnyTokenRetrieved) receiving correctly the token given by B2c auth. The callback onRedirect is also being call correctly and i am able to navigate to another screen (my home screen). My only issue, is that after logging in the browser can't find the redirect url of the schema, the message shown in the browser of the mobile phone after login is: .com.example/authapp://oauthredirect/?code........  could not be loaded because net::ERR_UNKNOWN_URL_SCHEME

I had created  (in android) a schema in the manifest adding in the activity tag 
 ```
<intent-filter>
    <action android:name="android.intent.action.VIEW" />

    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />

    <data
        android:scheme="com.example.authapp"
        android:host="oauthredirect"
        />
</intent-filter>
```

I tried to handle the url by installing the library uni_links  and adding a listener in the main function :

```
class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    initUniLinks();

    // TODO: implement initState
    super.initState();
  }

  void initUniLinks() async {
    getInitialLink().then((String? link) {
      if (link != null) {
        // Handle the link
      }
    });

    linkStream.listen((String? link) {
      if (link != null &&
          link.startsWith('com.example.authapp://oauthredirect')) {
        final Uri uri = Uri.parse(link);
        final String code = uri.queryParameters['code']!;
        // Now you have the code, proceed with your authentication flow
      }
      if (link != null) {
        // Handle the link
      }
    }, onError: (err) {
      // Handle the error
    });
  }
```
  
  But when I debug the code, the breakpoint in the listener  (breakpoint in line    if (link != null &&
          link.startsWith('com.example.authapp://oauthredirect')) ) is never reached.

I am a little bit lost what I need to do in order to show instead of a broken url text a loading progress or something like that during this fraction of second between the the token retrieved and the redirect callback that is sending the user to the home page. 

Thanks.

**Comment by mohanajuhi166** [comment]
@eugedebe can you try providing the uri as a route within the flutter app ?
 for example `/home_screen` or `/app-screen` etc? 
 what error do you get?

**Comment by filip8600** [comment]
For me, the solution was going from a redirect url like this: 

`msal<clientid>://auth` 

to 

`https://<tenant>.b2clogin.com/oauth2/nativeclient`

**Comment by mohanajuhi166** [comment]
closing as solution provided by @filip8600 . Thanks!
