### ISSUE TITLE
ERROR the request does not contains a client id parameter

### ISSUE THREAD

**Issue by lucahttp** [microsoft/aad_b2c_webview#3]
![image](https://user-images.githubusercontent.com/32082555/222977180-0ca6d73e-1bc5-44ff-ad50-a4a2673e7ab7.png)

code
![image](https://user-images.githubusercontent.com/32082555/222977255-682a6ac2-30b1-443c-b134-8bd4f04144e7.png)

**Comment by mohanajuhi166** [comment]
@lucahttp thanks for raising the issue. I will take this up and push the changes asap.

**Comment by mohanajuhi166** [comment]
@lucahttp can you try the below url for userFlowUrl
`https://<host>.b2clogin.com/<host>.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_signinup&client_id=<client_id>&nonce=defaultNonce&redirect_uri=<redirect_uri>&scope=openid&response_type=id_token&prompt=login`

in our next release, we will concatenate using client_id and redirect url and you wouldn't have to do this anymore. Please expect the release by end of this week.

**Comment by mohanajuhi166** [comment]
this is fixed now in release 0.0.44

**Comment by lucahttp** [comment]
Thank you
