### ISSUE TITLE
When ios wrapper will be release 

### ISSUE THREAD

**Issue by learntechi82** [microsoft/aad_b2c_webview#31]
Dear Microsoft team 

Is there any plan to release  iOS platform support ? 

Thank you

**Comment by mohanajuhi166** [comment]
Hello, if there is a requirement , would love to hear the usecase. We can then release the feature as it's not implemented yet.

**Comment by jnelle** [comment]
@learntechi82 it does work for me on iOS

**Comment by AlissonMMenezes** [comment]
For me it only worked when I added this as a redirect url:

  final aadB2CRedirectURL = 'customScheme://your_bundle_id/auth';

**Comment by mohanajuhi166** [comment]
Closing this ,as redirect uri solves the issue
