### ISSUE TITLE
Google Sign In issue

### ISSUE THREAD

**Issue by jnelle** [microsoft/aad_b2c_webview#35]
Hi,

I've added Google as an identity provider to my Azure Entra instance. Unfortunately I faced the following error message from after trying to sign in via Google.

<img width="490" alt="image" src="https://github.com/microsoft/aad_b2c_webview/assets/36324542/01b6978f-3516-4e58-aee0-2deadcc15c98">

You'll find the description of the error message here:
https://support.google.com/accounts/answer/12917337?hl=en#403disallowed&zippy=%2Cdisallowed-useragent

It seems like an user agent is missing.

**Comment by mohanajuhi166** [comment]
Fixed by PR from @jnelle
